version: "3.8"

services:
  server:
    container_name: "MGT_Webserver"
    image: "mgt-webserver:latest"
    ports:
      - "24449:80"
    volumes:
      - "mgt_skins:/app/static/skins"
      - "mgt_teams:/app/static/teams"

volumes:
  mgt_skins:
  mgt_teams: